### ISSUE TITLE
[🐞] Bug Report : Paypal screen freezing

### ISSUE THREAD

**Issue by salahelsayed99** [paypal/paypalcheckout-ios#81] opened 2021-11-15 10:36 UTC
### 🐞 Describe the Bug
The Paypal web screen doesn't pop up and the screen freezing i solve this bug with work around in facebook and google sign in but doesn't work in this case.

### 🌍 Environment

- iOS version: - 14.7
- SDK version (`Checkout.version`): - 0.77

https://user-images.githubusercontent.com/56044121/141766900-c2b893e5-fffa-4ed6-b711-5ed349a90b7f.mp4

**Comment by minhthenguyen** [comment] 2021-11-16 21:06
Hi @salahelsayed99 
I wasn't able to reproduce this bug. Can you share with us your integration code?
And it looks like your integration with facebook/google sign in also encountered the same issue, did you happen to know what caused the issue, and how did you work around it?

**Comment by salahelsayed99** [comment] 2021-11-17 08:14
Hello ,
Thank you for your respond, the app was implemented in 2018 and i don't know the reason of this bug in any pop up web view so i searched for a work around for this and it worked for me, you can check it in the screenshoots.

<img width="917" alt="Screen Shot 2021-11-17 at 10 11 06 AM" src="https://user-images.githubusercontent.com/56044121/142161107-2da7c473-2b5c-40b2-b07b-45905efad702.png">

<img width="917" alt="Screen Shot 2021-11-17 at 10 11 26 AM" src="https://user-images.githubusercontent.com/56044121/142161119-4583d446-19ea-43d3-883a-3dc0d5d0e3b9.png">

**Comment by salahelsayed99** [comment] 2021-11-22 10:38
Hi @minhthenguyen  any updates on this issue please ?

**Comment by minhthenguyen** [comment] 2021-11-29 22:58
@salahelsayed99 
Sorry for the delay. Can you provide the code for how your view controller is setup? Or a small sample app with the same view controller configuration where we can reproduce this bug would be very helpful.
Right now I haven't been able to reproduced it so it's hard to pinpoint where the issue is.

**Comment by salahelsayed99** [comment] 2021-11-30 10:36
Hi @minhthenguyen  never mind, the problem is that bottom sheet appears before the web pop up i should put my workaround code in this screen, if the web view pop without this bottom sheet the problem will be solved.

This problem will not appear if i make a new project i already tried to make a demo and it works fine, the problem is in my old version code and like i said before it happen in facebook login and google but this workaround solved the issue.

**Comment by minhthenguyen** [comment] 2021-11-30 23:36
Ah that's great to hear, I'm glad it's resolved.
I'll close this issue for now, but please feel free to open another if there are further issues down the line :smile:

**Closed by minhthenguyen** 2021-11-30 23:36 UTC
Labels: bug
