### ISSUE TITLE
[🐞] None of the Checkout callbacks are called when running the app on a real device

### ISSUE THREAD

**Issue by santiagofm** [paypal/paypalcheckout-ios#72] opened 2021-10-22 17:01 UTC
Hey guys!

I'm seeing this really weird behavior on our own (React Native) app, but before creating this issue i noticed I can repro it on your sample app so i'll stick to it.

### 🐞 Describe the Bug
- When running the app on an ios simulator everything seems to work fine, i can start the checkout flow programmatically, set the `orderId` with one generated server-side, sign in, pay and the `onApprove`/`onCancel`/`onError` callbacks fire as expected.
- When running the same app on a real device (either from Xcode or through a Testflight build) everything seems to work fin up until the Checkout SDK needs to handle the whole signin/pay. Seems like it just refuses to handle the thing on it's own and just opens the checkout flow on a webview  🤷🏻. Although i can signin and pay, none of the SDK callbacks get called so. the app is basically stuck.

### 🔬 Minimal Reproduction
1. clone https://github.com/paypal/paypalcheckout-samples-ios
2. Set both `clientId` & `returnUrl` on the `PayPal` class in the Paypal.API file
3. Modify the `CheckoutViewController`'s `startNativeCheckout` to use a pre-created `orderId`:
```swift
/// Request an ECToken/orderID/payToken with PayPal Orders API,
    /// then checkout with `ECToken`/`orderID`/`payToken`
    case 1:
      Checkout.start(createOrder: { action in
        action.set(orderId: "66S90911NR6185831")
      },
      onApprove: { approval in
        self.processOrderActions(with: approval)
      },
      onCancel: {
        print("Checkout cancelled")
      },
      onError: { errorInfo in
        print("Checkout failed with error info \(errorInfo.error.localizedDescription)")
      }
    )
```
4. Run the app and checkout

### 😕 Actual Behavior
The SDK just doesn't seem to want to deal with the checkout and just opens a webview, ui gets a little broken too and I can see multiple "Unable to simultaneously satisfy constraints." warnings on the Xcode console.

See recording:

<p align="center">
<img src="https://user-images.githubusercontent.com/6749415/138493654-312499ad-d383-4714-8ce2-3bc3627d76be.MP4" width="300" />
</p>

### 🤔 Expected Behavior
I would expect the checkout to succeed and the callbacks to fire, like they do when running on a simulator:

<p align="center">
<img src="https://user-images.githubusercontent.com/6749415/138493866-d228d6e6-686f-48e3-aebc-51cb846668ee.gif" width="300" />
</p>

### 🌍 Environment

- iOS version: 15.0.1 (iPhone 8), also reprod on 14.8, 15.0.2
- SDK version (`Checkout.version`): 0.70.0 on sample app, also repro on our app w/ 0.73.0

### ➕ Additional Context
- I couldn't find extra info I to provide, the Xcode console does not show any errors and the `onError` callback isn't called.
- The fact that I can repro this using the sample app makes me think there's something we are not setting up correctly? I've double checked both client id & return url are correct, the native checkout SDK checkbox in the dashboard is enabled & login with paypal is enabled too.

Let me know if there's any other info i can provide and i'll do so, thanks!

**Comment by jonathajones** [comment] 2021-11-01 15:06
Hi @santiagofm  - We looked into some of the logs, and it looks like you're receiving the web fallback experience because of an ineligible buyer country associated with the buyer account in sandbox. Are you using the same end user account for testing across android and iOS? 

We are still looking into the double login on web fallback. 
Just wanted to give you an update!

**Comment by quintonpryce** [comment] 2021-11-03 13:44
Hi @jonathajones I'm experiencing this same "double login issue" as @santiagofm. I wanted to add one thing here, whenever I start up the checkout I get the following errors. I did attempt to fix it by adding the query schemes but it didn't fix my issue so I removed them.

```
2021-11-03 06:37:10.150008-0700 1v1Me[6261:1905912] -canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
2021-11-03 06:37:10.150506-0700 1v1Me[6261:1905912] -canOpenURL: failed for URL: "sileo://" - error: "This app is not allowed to query for scheme sileo"
2021-11-03 06:37:10.151050-0700 1v1Me[6261:1905912] -canOpenURL: failed for URL: "undecimus://" - error: "This app is not allowed to query for scheme undecimus"
2021-11-03 06:37:10.151487-0700 1v1Me[6261:1905912] -canOpenURL: failed for URL: "zbra://" - error: "This app is not allowed to query for scheme zbra"
2021-11-03 06:37:10.151938-0700 1v1Me[6261:1905912] -canOpenURL: failed for URL: "tweakbox://" - error: "This app is not allowed to query for scheme tweakbox"
2021-11-03 06:37:10.152808-0700 1v1Me[6261:1905912] -canOpenURL: failed for URL: "emus4u://" - error: "This app is not allowed to query for scheme emus4u"
2021-11-03 06:37:10.197543-0700 1v1Me[6261:1906303] [assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
2021-11-03 06:37:10.197592-0700 1v1Me[6261:1906303] [ProcessSuspension] 0x11bbfa040 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=6264, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
```

On Create: 

```
(lldb) p State.correlationIDs.fundingEligibilityDebugID
(String?) $R3 = nil
(lldb) p State.correlationIDs.eligibilityDebugID
(String?) $R4 = nil
```

On Approve:

```
(lldb) p State.correlationIDs.fundingEligibilityDebugID
(String?) $R6 = nil
(lldb) p State.correlationIDs.eligibilityDebugID
(String?) $R7 = nil

(PayPalCheckout.Approval) $R9 = 0x0000000281087fc0 {
  ObjectiveC.NSObject = {
    isa = PPCApproval
  }
  data = 0x00000002820a5ea0 {
    ObjectiveC.NSObject = {
      isa = PPCApprovalData
    }
    cart = nil
    buyer = nil
    payerID = "LHDFWLMVSLHKU"
    ecToken = "1NC14493AR9257343"
    intent = "sale"
    returnURL = Failed to get the 'some' field from optional 'returnURL'
    paymentID = nil
  }
  actions = 0x0000000281084540 {
    ObjectiveC.NSObject = {
      isa = PPCOrderActions
    }
  }
}
```

**Comment by quintonpryce** [comment] 2021-11-03 13:46
This is the approval object when I go through the simulator with the same order creation steps:

```
(PayPalCheckout.Approval) $R4 = 0x00006000036c5100 {
  ObjectiveC.NSObject = {
    isa = PPCApproval
  }
  data = 0x000060000064f2a0 {
    ObjectiveC.NSObject = {
      isa = PPCApprovalData
    }
    cart = some {
      cartID = "48N61707VR1242034"
      intent = "SALE"
      _items = 0 values {}
      shippingMethods = 0 values {}
      amounts = some {
        handlingFee = 0x00006000013dfc00 {
          ObjectiveC.NSObject = {
            isa = PPCUnitAmount
          }
          value = "0.00"
          currencyCodeString = "USD"
          currencyFormat = nil
        }
        insurance = 0x00006000013de160 {
          ObjectiveC.NSObject = {
            isa = PPCUnitAmount
          }
          value = "0.00"
          currencyCodeString = "USD"
          currencyFormat = nil
        }
        shippingAndHandling = 0x00006000013dfde0 {
          ObjectiveC.NSObject = {
            isa = PPCUnitAmount
          }
          value = "0.00"
          currencyCodeString = "USD"
          currencyFormat = nil
        }
        subtotal = 0x00006000013de700 {
          ObjectiveC.NSObject = {
            isa = PPCUnitAmount
          }
          value = "0.00"
          currencyCodeString = "USD"
          currencyFormat = nil
        }
        tax = 0x00006000013de220 {
          ObjectiveC.NSObject = {
            isa = PPCUnitAmount
          }
          value = "0.00"
          currencyCodeString = "USD"
          currencyFormat = nil
        }
        total = 0x00006000013dcb40 {
          ObjectiveC.NSObject = {
            isa = PPCUnitAmount
          }
          value = "10.00"
          currencyCodeString = "USD"
          currencyFormat = nil
        }
      }
      _cancelURL = nil
      _returnURL = nil
      _total = 0x00006000013de7c0 {
        ObjectiveC.NSObject = {
          isa = PPCUnitAmount
        }
        value = "10.00"
        currencyCodeString = "USD"
        currencyFormat = nil
      }
      paymentID = nil
      billingToken = nil
      billingType = nil
    }
    buyer = some {
      userId = "LHDFWLMVSLHKU"
      name = nil
      _locale = nil
      _email = some {
        stringValue = "quintonpryce@gmail.com"
      }
      profileImage = nil
      _addresses = nil
    }
    payerID = "LHDFWLMVSLHKU"
    ecToken = "48N61707VR1242034"
    intent = "SALE"
    returnURL = Failed to get the 'some' field from optional 'returnURL'
    paymentID = nil
  }
  actions = 0x00006000036c4340 {
    ObjectiveC.NSObject = {
      isa = PPCOrderActions
    }
  }
}
```

**Comment by quintonpryce** [comment] 2021-11-03 13:51
@jonathajones if you need to live debug this I can either add you to a slack channel or we can do a google meet to try and iterate a bit quicker on this issue. Let me know whatever works for you, happy to continue to chat through this thread too. I will check back hourly on EST.

**Comment by jonathajones** [comment] 2021-11-03 18:23
We're still engaging with the web team on double login scenario, I'll update here when we have more information to share. In our next release we will have a fix in place to properly set the `State.correlationIDs.eligibilityDebugID` value.

**Comment by quintonpryce** [comment] 2021-11-03 18:33
If you want I can point my sdk to a different branch to get you the eligibility debug id quicker.

**Comment by jonathajones** [comment] 2021-11-03 18:56
@quintonpryce Two questions:
1. What's the merchant and user region? 
2. Are you using the billing agreement flow?

**Comment by quintonpryce** [comment] 2021-11-03 19:38
@jonathajones 
1. Our merchant & user region is USA
2. No we are not using the bulling agreement flow

**Comment by jonathajones** [comment] 2021-11-03 20:30
@quintonpryce Looking up the analytics logs for the tokens you sent on, it looks like you're seeing the same fallback reason that @santiagofm is seeing - the `buyerCountry` associated with the buyer's account is ineligible. is the sandbox buyer account you're using to test the SDK associated with a different country?

**Comment by jonathajones** [comment] 2021-11-03 20:40
@quintonpryce What version of the SDK are you on?

**Comment by quintonpryce** [comment] 2021-11-03 21:25
@jonathajones  0.77

**Comment by quintonpryce** [comment] 2021-11-11 20:50
@jonathajones Any updates on this issue?

**Comment by jonathajones** [comment] 2021-11-11 22:05
Sorry for the radio silence - we're still actively in progress resolving the issue. Will update you with an ETA once the fix is identified and in place.

**Comment by santiagofm** [comment] 2021-12-10 16:12
hey @jonathajones 👋🏻 ! Was this addressed in the 0.79 release ?

**Comment by jonathajones** [comment] 2021-12-10 21:53
Hi @santiagofm ! 
Thanks for checking back in. The `0.79.0` release does contain a fix to the issue of having to log in twice. The issue was related to improper scoping on some access tokens created by the SDK. 

Please do integrate with it and let me know if you're still experiencing the issue. 
Note - the `0.79.0` release was created on Xcode 13. We'll be cutting a new version of the SDK next week generated from Xcode 12.4 - the bump was unintentional.

**Comment by alihanaktay** [comment] 2021-12-22 07:16
Same double login issue happens on both production & sandbox environment, any update on that?

**Comment by jonathajones** [comment] 2022-01-04 16:23
@alihanaktay - What version of the checkout SDK are you on? 

If you're still experiencing this after updating to version `0.79.0`, please open a new issue with reproduction steps. There have been a couple issues triaged here and I'd like to keep the issues focused on a single problem, when possible.

**Comment by alihanaktay** [comment] 2022-01-25 07:52
Hi @jonathajones, the version number is 0.79.0, 

Since other users open an issue about that I'm not opening new issue.

**Closed** 2022-12-14 18:36 UTC
Labels: bug
